"""Actual Chromium/WebGL verification; no raster substitute for terrain geometry."""
import json,os,subprocess
from pathlib import Path
from playwright.sync_api import sync_playwright
R=Path(__file__).resolve().parents[3];Q=R/'qa/m11a-p02';Q.mkdir(exist_ok=True,parents=True)
server=subprocess.Popen(['python','-m','http.server','8771','--directory',str(R/'apps/campus/dist')],stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
checks=[];errors=[];screens=[]
def check(name,value,detail=None):
 checks.append({'name':name,'passed':bool(value),'detail':detail});print(name,bool(value),flush=True)
 if not value:raise AssertionError(name+': '+str(detail)[:2200])
try:
 with sync_playwright() as pw:
  browser=pw.chromium.launch(headless=True,args=['--no-sandbox','--enable-unsafe-swiftshader','--use-angle=swiftshader','--disable-dev-shm-usage'])
  page=browser.new_page(viewport={'width':1440,'height':1000},device_scale_factor=1)
  page.on('pageerror',lambda e:errors.append(str(e)));page.on('console',lambda e:errors.append(e.text) if e.type=='error' else None)
  page.goto('http://127.0.0.1:8771/?clean=1',wait_until='networkidle');page.wait_for_function('window.__YALI_P02__?.ready');page.wait_for_timeout(300)
  state=page.evaluate('window.__YALI_M11A__.state()');check('terrain initialized',state['report']['passed'],state);check('authorized P02 layout constraints',page.evaluate('window.__YALI_M10__.report.passed'))
  check('actual entrance5 percent H grade',page.evaluate("(()=>{const a=window.__YALI_M11A__,at=(z)=>a.probeGround(0,z).find(h=>h.name.startsWith('M11A-road-'))?.y;return Math.abs(at(24)-at(4)-1)<.003})()"))
  (Q/'effective-layout.json').write_text(json.dumps(page.evaluate('window.__YALI_P02__.layout'),ensure_ascii=False,indent=2));(Q/'patch-checks.json').write_text(json.dumps(page.evaluate('window.__YALI_P02__.report'),ensure_ascii=False,indent=2))
  roots=page.evaluate('window.__YALI_M11A__.getRoots()');snapshot=page.evaluate('window.__YALI_M10__.geometrySnapshot()');(Q/'geometry-snapshot.json').write_text(json.dumps(snapshot,indent=2))
  supports=page.evaluate('''()=>{const a=window.__YALI_M11A__,d=a.exportData();let fail=[],n=0,max=0;for(const p of d.profiles){for(let i=0;i<p.samples.length;i+=2){const q=p.samples[i],hits=a.probeGround(q.x,q.z),road=hits.find(h=>h.name.startsWith('M11A-road-')||h.name.startsWith('M11A-joint-'));n++;if(!road)fail.push([p.from,p.to,i,'NO_ROAD']);else{max=Math.max(max,Math.abs(road.y-q.y));if(Math.abs(road.y-q.y)>.025)fail.push([p.from,p.to,i,q.y,road.y]);}}}return {n,max,fail};}''')
  (Q/'road-support-probes.json').write_text(json.dumps(supports,indent=2));check('all45 draped road centerlines supported',not supports['fail'],supports)
  widths=page.evaluate('''()=>{const a=window.__YALI_M11A__,d=a.exportData(),bad=[];let n=0;for(const p of d.profiles){const q=p.samples[Math.floor(p.samples.length/2)],a0=p.samples[0],a1=p.samples.at(-1),dx=a1.x-a0.x,dz=a1.z-a0.z,len=Math.hypot(dx,dz);for(const sign of [-1,1]){const x=q.x+dz/len*(p.width/2-.05)*sign,z=q.z-dx/len*(p.width/2-.05)*sign;n++;if(!a.probeGround(x,z).some(h=>h.name.startsWith('M11A-road-')))bad.push([p.from,p.to,sign]);}}return {n,bad};}''');check('full road widths supported',not widths['bad'],widths)
  clearance=page.evaluate('''()=>{const a=window.__YALI_M11A__,d=a.exportData();let fail=[],n=0;for(const p of d.profiles){for(let i=1;i<p.samples.length;i+=4){const u=p.samples[Math.max(0,i-4)],v=p.samples[i];for(const height of [.25,1.7,2.1]){const h=a.probeActual([u.x,u.y+height,u.z],[v.x,v.y+height,v.z]);n++;if(h.length)fail.push({from:p.from,to:p.to,i,height,hits:h.slice(0,3)});}}}return {n,fail};}''');(Q/'road-clearance.json').write_text(json.dumps(clearance,indent=2));check('actual route clearance after grade change',not clearance['fail'],clearance)
  stairs=page.evaluate('''()=>{const a=window.__YALI_M11A__,d=a.exportData(),bad=[],rows=[];for(const s of d.stairs){for(let i=0;i<s.steps;i++){const t=(i+.5)/s.steps,x=s.start[0]+(s.end[0]-s.start[0])*t,z=s.start[1]+(s.end[1]-s.start[1])*t,expected=s.base+.04+(i+1)*s.rise/s.steps,h=a.probeGround(x,z).find(h=>h.name===s.id+'-step-'+(i+1));rows.push({id:s.id,step:i+1,expected,actual:h?.y});if(!h||Math.abs(h.y-expected)>.002)bad.push(rows.at(-1));}const dx=(s.end[0]-s.start[0])/s.length,dz=(s.end[1]-s.start[1])/s.length,y=s.top+1.7;const hits=a.probeActual([s.end[0]-dx*.2,y,s.end[1]-dz*.2],[s.end[0]+dx*.6,y,s.end[1]+dz*.6]);if(hits.length)bad.push({id:s.id,blockedTop:hits});}return {rows,bad};}''');(Q/'entrance-step-probes.json').write_text(json.dumps(stairs,indent=2));check('17 physical entry steps and4 top portals',not stairs['bad'],stairs)
  toilet=page.evaluate('''()=>{const a=window.__YALI_M11A__,l=window.__YALI_M10__.layout,h=a.state().anchors['25'].floor,rows=[],bad=[];for(const f of l.toilet25.floors){const y=f.elevation+h+.04;for(const z of [218.9,229.1]){const pts=[[-6,y+1.7,224],[-8.1,y+1.7,224],[-8.1,y+1.7,z],[-10,y+1.7,z]];for(let j=1;j<pts.length;j++){const hits=a.probeActual(pts[j-1],pts[j]);if(hits.length)bad.push({level:f.level,z,hits});}const down=a.probeActual([-8.1,y+.3,z],[-8.1,y-.3,z]);const ok=down.some(v=>v.name==='25-L'+f.level+'-full-floor');rows.push({level:f.level,z,supported:ok});if(!ok)bad.push(rows.at(-1));}}return {rows,bad};}''');(Q/'toilet-level-probes.json').write_text(json.dumps(toilet,indent=2));check('4 toilet slabs / 8 end-door routes retained',not toilet['bad'],toilet)
  gym=page.evaluate("()=>{const a=window.__YALI_P02__,b=window.__YALI_M11A__,pts=a.galleryRoute(),bad=[],support=[],clear=[];for(const q of pts){const hits=a.support(...q);support.push({point:q,hits});if(!hits.some(h=>Math.abs(h.y-q[1])<.015))bad.push({type:'floor',point:q,hits});}for(let i=1;i<pts.length;i++){const u=pts[i-1],v=pts[i],hits=a.probe([u[0],u[1]+1.7,u[2]],[v[0],v[1]+1.7,v[2]]);clear.push({i,hits});if(hits.length)bad.push({type:'blocked',i,hits});}const h=b.state().anchors['03'].floor;const front=a.probe([-19,h+1.7,45],[-29,h+1.7,45]),closed=a.probe([-45,h+1.7,20],[-45,h+1.7,27]),contact=a.probe([-60,h+1.7,65.4],[-60,h+1.7,66.6]);return {support,clear,bad,front,closed,contact};}")
  (Q/'gym-gallery-probes.json').write_text(json.dumps(gym,indent=2));check('28 spectator treads with supported landing and viewing aisle',not gym['bad'],gym['bad']);check('real main-road front doorway',not gym['front'],gym['front']);check('old north doorway closed',bool(gym['closed']),gym['closed']);check('shared music contact remains open',not gym['contact'],gym['contact'])
  (Q/'gym-geometry.json').write_text(json.dumps(page.evaluate('window.__YALI_P02__.geometrySnapshot()'),indent=2))
  check('actual gym height matches H parameter',page.evaluate("(()=>{const a=window.__YALI_P02__,h=window.__YALI_M11A__.state().anchors['03'].floor;return Math.abs(Math.max(...Object.values(a.geometrySnapshot()).filter(x=>x.role==='upper-shell').map(x=>x.max[1]))-h-a.parameters.gym.height)<.002})()"))
  for view in ['top','overview','terrain-entrance','gym-p02-front','gym-p02-oblique','gym-p02-loop','gym-p02-stair','gym-p02-gallery','terrain-longya','terrain-gap','courts-to-gym']:
   page.evaluate('(v)=>window.__YALI_M11A__.setView(v)',view);page.wait_for_timeout(450);page.screenshot(path=str(Q/(view+'.png')));screens.append(view+'.png');check('camera '+view,True)
  page.evaluate("window.__YALI_P02__.setCutaway(true);window.__YALI_M11A__.setView('gym-p02-gallery')");page.wait_for_timeout(300);page.screenshot(path=str(Q/'gallery-cutaway.png'));screens.append('gallery-cutaway.png');check('gym cutaway hides only upper shell',page.evaluate('Object.values(window.__YALI_P02__.geometrySnapshot()).filter(x=>x.role===\"upper-shell\").every(x=>!x.visible)'));page.evaluate("window.__YALI_P02__.setCutaway(false)")
  page.evaluate("window.__YALI_M11A__.setView('top');window.__YALI_M11A__.setEnabled(false)");page.wait_for_timeout(200);page.screenshot(path=str(Q/'zero-datum-comparison.png'));screens.append('zero-datum-comparison.png')
  low=page.evaluate('window.__YALI_M11A__.getRoots()');l=json.loads((R/'data/m10/campus-layout.json').read_text());check('comparison restores all root Y',all(abs(low[f['id']][1]-(.08 if f['id']=='23' else f['position'][1]))<1e-7 for f in l['facilities'] if f['position']))
  page.evaluate('for(let i=0;i<8;i++){window.__YALI_M11A__.setEnabled(true);window.__YALI_M11A__.setEnabled(false);}window.__YALI_M11A__.setEnabled(true)');check('8 toggles no accumulated displacement',page.evaluate('window.__YALI_M11A__.getRoots()')==roots)
  check('actual shared gym/music floor',abs(roots['03'][1]-roots['24'][1])<1e-8);check('actual shared main/toilet floor',abs(roots['15'][1]-roots['25'][1])<1e-8)
  page.evaluate("document.body.classList.remove('clean')");page.locator('#inspect-btn').click()
  with page.expect_download() as dl:page.locator('#terrain-export').click()
  fp=Q/'browser-export.json';dl.value.save_as(fp);check('terrain export action',json.loads(fp.read_text())['version']=='M1.1-A.Patch02');page.locator('#close-inspector').click()
  page.locator('#tour-btn').click();page.wait_for_function('window.__YALI_M10__.getState().tour');check('tour relative eye height',page.evaluate('(()=>{const p=window.__YALI_M10__.getState().camera;return Math.abs(p[1]-window.__YALI_M11A__.groundEye(p[0],p[2]))<.01})()'))
  page.keyboard.press('Escape');check('tour exits',not page.evaluate('window.__YALI_M10__.getState().tour'))
  page.set_viewport_size({'width':390,'height':844});page.wait_for_timeout(300);page.evaluate("window.__YALI_M11A__.setView('top')");page.wait_for_timeout(200);page.screenshot(path=str(Q/'mobile.png'));screens.append('mobile.png');check('mobile viewport resized',page.evaluate('window.__YALI_M10__.getState().canvas[0]')==390)
  page.goto((R/'artifacts/m11a/Yali_M1_1_A_Viewer.html').as_uri(),wait_until='load');page.wait_for_function('window.__YALI_P02__?.ready');check('standalone file startup',page.evaluate('window.__YALI_M11A__.state().enabled'))
  check('no page/shader errors',not errors,errors);browser.close()
finally:
 server.terminate();server.wait(timeout=10)
 (Q/'browser-report.json').write_text(json.dumps({'version':'M1.1-A.Patch02','checks':checks,'passed':bool(checks) and all(c['passed'] for c in checks),'complete':bool(checks) and checks[-1]['name']=='no page/shader errors','errors':errors,'screenshots':screens,'source_input':os.getenv('GITHUB_SHA'),'environment':'Chromium software WebGL, not device performance certification'},ensure_ascii=False,indent=2))
