import fs from 'node:fs';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import {createRequire} from 'node:module';
import {createHash} from 'node:crypto';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const viewer=path.resolve('artifacts/m11c-c2/Yali_C2_R1_Viewer.html'),out=path.resolve('qa/m11c-c2/browser');fs.mkdirSync(out,{recursive:true});
const sha=b=>createHash('sha256').update(b).digest('hex');
const browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage']});
const ctx=await browser.newContext({viewport:{width:1280,height:840}}),page=await ctx.newPage();const errors=[];page.on('pageerror',e=>errors.push(String(e)));await page.goto(pathToFileURL(viewer).href+'?diagnostics=1',{waitUntil:'load',timeout:600000});await page.waitForFunction(()=>window.__YALI_C1__?.state().ready,null,{timeout:600000});
async function canvasShot(pg,name){const data=await pg.evaluate(()=>{const r=window.__YALI_RENDER_RAW__;if(r?.renderFrame)r.renderFrame();else r.renderer.render(r.scene,r.camera());r.renderer.getContext().finish();return r.renderer.domElement.toDataURL('image/png');});fs.writeFileSync(path.join(out,name+'.png'),Buffer.from(data.split(',')[1],'base64'));return 'actual same-frame WebGL canvas readback';}
const checks=[];const methods={};const check=(name,pass,data)=>checks.push({name,pass:Boolean(pass),data});let st=await page.evaluate(()=>window.__YALI_C1__.state());check('C2 final student is active',st.avatar.finalStudent===true,st.avatar);check('C1 R1.2 mobile graphics policy inherited',Boolean(st.graphics),st.graphics);methods['01-gate-idle']=await canvasShot(page,'01-gate-idle');
await page.evaluate(()=>window.__YALI_C1__.drive({x:0,z:1,run:false},120));st=await page.evaluate(()=>window.__YALI_C1__.state());check('walk animation reached',st.avatar.animation==='walk',st.avatar);methods['02-walk']=await canvasShot(page,'02-walk');
await page.evaluate(()=>window.__YALI_C1__.drive({x:0,z:1,run:true},120));st=await page.evaluate(()=>window.__YALI_C1__.state());check('run animation reached',st.avatar.animation==='run',st.avatar);methods['03-run']=await canvasShot(page,'03-run');
await page.evaluate(()=>{window.__YALI_C1__.spawn('lane');window.__YALI_C1__.tick(.016)});methods['04-side-lane']=await canvasShot(page,'04-side-lane');
const mctx=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:3,isMobile:true,hasTouch:true});const mp=await mctx.newPage();await mp.goto(pathToFileURL(viewer).href+'?diagnostics=1',{waitUntil:'load',timeout:600000});await mp.waitForFunction(()=>window.__YALI_C1__?.state().ready,null,{timeout:600000});const ms=await mp.evaluate(()=>window.__YALI_C1__.state());check('mobile defaults to balanced raster policy',ms.graphics?.mode==='balanced',ms.graphics);check('mobile student remains final C2',ms.avatar.finalStudent===true,ms.avatar);methods['05-mobile']=await canvasShot(mp,'05-mobile');await mctx.close();
const files=fs.readdirSync(out).filter(f=>f.endsWith('.png')).map(f=>({file:f,sha256:sha(fs.readFileSync(path.join(out,f))),method:methods[path.basename(f,'.png')]}));const report={version:'C2.R1',viewerSHA256:sha(fs.readFileSync(viewer)),checks,errors,screenshots:files,passed:errors.length===0&&checks.every(c=>c.pass)&&files.length===5};fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2)+'\n');await browser.close();console.log(JSON.stringify(report));if(!report.passed)process.exit(1);
