import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {build} from '../../apps/campus/node_modules/esbuild/lib/main.js';
const root=fileURLToPath(new URL('../../',import.meta.url)),out=path.join(root,'artifacts/m11c-c1');
await fs.mkdir(out,{recursive:true});
const r=await build({entryPoints:[path.join(root,'apps/campus/src/main.ts')],bundle:true,metafile:true,absWorkingDir:root,format:'iife',target:'es2022',minify:true,write:false,outfile:'bundle.js',legalComments:'inline'});
const js=r.outputFiles.find(f=>f.path.endsWith('.js')).text.replace(/<\/script/gi,'<\\/script'),css=r.outputFiles.find(f=>f.path.endsWith('.css')).text;
const template=await fs.readFile(path.join(root,'apps/campus/index.html'),'utf8');
const html=template.replace('</head>',`<style>${css}</style></head>`).replace('<script type="module" src="/src/main.ts"></script>',()=>`<script>${js}</script>`);
const name='Yali_C1_R1_Viewer.html',digest=b=>createHash('sha256').update(b).digest('hex'),sha256=digest(html);
await fs.writeFile(path.join(out,name),html);
const files=[...new Set([...Object.keys(r.metafile.inputs).filter(f=>!f.includes('node_modules')).map(f=>path.relative(root,path.resolve(root,f))),'apps/campus/index.html','apps/campus/package.json','apps/campus/package-lock.json'])].sort();
const sources={};for(const f of files)sources[f]=digest(await fs.readFile(path.join(root,f)));
await fs.writeFile(path.join(out,'viewer-manifest.json'),JSON.stringify({file:name,sha256,bytes:Buffer.byteLength(html),version:'C1.R1',status:'IMPLEMENTED / REVIEW_PENDING',standard:'1.0',generatedAt:new Date().toISOString(),gitHead:execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim(),source:'Per-file digests identify exact runtime including an uncommitted worktree',sources},null,2)+'\n');
const notices=await Promise.all(['three/LICENSE','three-mesh-bvh/LICENSE'].map(async f=>f+'\n'+await fs.readFile(path.join(root,'apps/campus/node_modules',f),'utf8')));
notices.push('@dimforge/rapier3d-compat 0.20.0 — Apache-2.0\nOfficial repository: https://github.com/dimforge/rapier.js\nCopyright Dimforge / Rapier contributors. WASM embedded in offline Viewer.\nSee APACHE-2.0.txt.');
await fs.writeFile(path.join(out,'THIRD_PARTY_NOTICES.txt'),notices.join('\n\n'));
await fs.copyFile(path.join(root,'tools/m11c-c1/APACHE-2.0.txt'),path.join(out,'APACHE-2.0.txt'));
console.log(name,Buffer.byteLength(html),sha256);
