import {build} from '../../apps/campus/node_modules/esbuild/lib/main.js';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {applyPatch02} from '../../apps/campus/src/patch02-core.mjs';
import {buildPatch03Model} from '../../apps/campus/src/patch03-core.mjs';
import {buildPatch04Model} from '../../apps/campus/src/patch04-core.mjs';
import {buildBatch01Model,batch01Checks} from '../../apps/campus/src/batch01-core.mjs';
const root=fileURLToPath(new URL('../../',import.meta.url)),out=path.join(root,'artifacts/m11b-b01');fs.mkdirSync(out,{recursive:true});
const read=p=>JSON.parse(fs.readFileSync(path.join(root,p)));
const q=applyPatch02(read('data/m10/campus-layout.json'),read('data/m11a/terrain-input.json'),read('data/m11a/patch02/input.json'));
const t=buildPatch04Model(buildPatch03Model(q.layout,q.terrain,read('data/m11a/patch03/input.json')),read('data/m11a/patch04/input.json'));
const m=buildBatch01Model(q.layout,t,read('data/m11b/batch01/input.json'));
const checks=batch01Checks(q.layout,m);if(!checks.passed)throw Error(JSON.stringify(checks));
const result=await build({entryPoints:[path.join(root,'apps/campus/src/main.ts')],bundle:true,format:'iife',target:'es2022',minify:true,write:false,outfile:'bundle.js',legalComments:'inline'});
const js=result.outputFiles.find(f=>f.path.endsWith('.js')).text.replace(/<\/script/gi,'<\\/script'),css=result.outputFiles.find(f=>f.path.endsWith('.css')).text;
const html=fs.readFileSync(path.join(root,'apps/campus/index.html'),'utf8').replace('</head>',()=>`<style>${css}</style></head>`).replace('<script type="module" src="/src/main.ts"></script>',()=>`<script>${js}</script>`);
fs.writeFileSync(path.join(out,'Yali_M1_1_B_Batch01_Viewer.html'),html);
fs.writeFileSync(path.join(out,'THIRD_PARTY_NOTICES.txt'),'Three.js r180 / MIT\n'+fs.readFileSync(path.join(root,'apps/campus/node_modules/three/LICENSE'),'utf8'));
fs.writeFileSync(path.join(root,'data/m11b/batch01/resolved-buildings.json'),JSON.stringify(m.exportData(),null,2)+'\n');
fs.writeFileSync(path.join(root,'data/m11a/patch04/resolved-terrain.json'),JSON.stringify(t.exportData(),null,2)+'\n');
fs.writeFileSync(path.join(out,'Yali_M1_1_B_Batch01_Checks.json'),JSON.stringify(checks,null,2)+'\n');
console.log('Standalone',Buffer.byteLength(html),'bytes; parts',m.parts.length,'checks',checks.results.length);
