import { readFileSync } from 'node:fs';
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { checkLayout, footprint, bounds, courtRects, toBlender, fromBlender } from '../../apps/campus/src/layout-core.mjs';
const layout=JSON.parse(readFileSync(new URL('../../data/m10/campus-layout.json',import.meta.url),'utf8'));
const report=checkLayout(layout);
for(const row of report.results)test(row.id,()=>assert.equal(row.passed,true,row.detail));
test('coordinate conversion roundtrips',()=>assert.deepEqual(fromBlender(toBlender([17,3.8,-11])),[17,3.8,-11]));
test('null footprint stays unknown',()=>assert.equal(footprint(layout.facilities.find(f=>f.id==='22')),null));
test('world footprint dimensions match H values',()=>{const f=layout.facilities.find(v=>v.id==='24'),b=bounds(f);assert.equal(b.maxX-b.minX,16);assert.equal(b.maxZ-b.minZ,12);});
test('six distinct court rectangles in perimeter',()=>{const b=bounds(layout.facilities.find(f=>f.id==='06'));for(const c of courtRects(layout)){assert.ok(c.minX>b.minX&&c.maxX<b.maxX&&c.minZ>b.minZ&&c.maxZ<b.maxZ);}});
test('regression: one metre gap fails',()=>{const l=structuredClone(layout);l.facilities.find(f=>f.id==='06').position[0]+=1;assert.equal(checkLayout(l).passed,false);});
test('regression: missing floor bridge fails',()=>{const l=structuredClone(layout);l.connections.pop();assert.equal(checkLayout(l).passed,false);});
test('regression: music gets one storey fails',()=>{const l=structuredClone(layout);l.facilities.find(f=>f.id==='24').floors=1;assert.equal(checkLayout(l).passed,false);});
test('regression: office moved onto route fails',()=>{const l=structuredClone(layout);l.facilities.find(f=>f.id==='07').position[0]=0;assert.equal(checkLayout(l).results.find(r=>r.id==='EXTERIOR_ROUTES_CLEAR').passed,false);});
test('regression R2: canopy disabled fails',()=>{const l=structuredClone(layout);l.sports.canopy.enabled=false;assert.equal(checkLayout(l).results.find(r=>r.id==='R2_CANOPY_FULL_LENGTH').passed,false);});
test('regression R2: off-centre bridges fail',()=>{const l=structuredClone(layout);l.connections.forEach(v=>v.z=218.05);assert.equal(checkLayout(l).results.find(r=>r.id==='R2_MIDPOINT_LINK').passed,false);});
test('regression R2: old sandpit location fails',()=>{const l=structuredClone(layout);l.facilities.find(f=>f.id==='23').position=[128,0,198];assert.equal(checkLayout(l).results.find(r=>r.id==='R2_PIT_ON_REAR_RIGHT').passed,false);});
test('regression R2: missing side path edge fails',()=>{const l=structuredClone(layout);l.navigation.edges=l.navigation.edges.filter(v=>!v.includes('side-mid'));assert.equal(checkLayout(l).results.find(r=>r.id==='R2_REQUIRED_CHAIN_1').passed,false);});
test('regression R2: rear door isolated fails',()=>{const l=structuredClone(layout);l.navigation.edges=l.navigation.edges.filter(v=>!v.includes('main-rear'));assert.equal(checkLayout(l).results.find(r=>r.id==='R2_REQUIRED_CHAIN_3').passed,false);});
test('regression R2: library wrong-side detour fails',()=>{const l=structuredClone(layout);l.navigation.edges.push(['garden-entry','library-entry']);assert.equal(checkLayout(l).results.find(r=>r.id==='R2_OLD_LIBRARY_DETOUR_REMOVED').passed,false);});
test('regression R2: gym-link gap fails',()=>{const l=structuredClone(layout);l.buildingLinks[0].path[0][0]-=1;assert.equal(checkLayout(l).results.find(r=>r.id==='R2_GYM_MUSIC_LINK').passed,false);});
test('regression R2: large former toilet fails',()=>{const l=structuredClone(layout);l.facilities.find(f=>f.id==='26').size=[6,3.3,4.5];assert.equal(checkLayout(l).results.find(r=>r.id==='R2_POOL_TOILET_SMALLER').passed,false);});
test('regression R2: bridge below headroom fails',()=>{const l=structuredClone(layout);l.connections[1].y=1.9;assert.equal(checkLayout(l).results.find(r=>r.id==='R2_ROUTES_CLEAR_STRUCTURES').passed,false);});
test('regression R2: tour skips a graph edge fails',()=>{const l=structuredClone(layout);l.navigation.tourPath=['gate','library-entry'];assert.equal(checkLayout(l).results.find(r=>r.id==='R2_TOUR_USES_GRAPH').passed,false);});
