import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';
import {buildTerrainModel,terrainChecks} from '../../apps/campus/src/terrain-core.mjs';
const root=fileURLToPath(new URL('../../',import.meta.url)),load=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));
const l=load('data/m10/campus-layout.json'),s=load('data/m11a/terrain-input.json'),t=buildTerrainModel(l,s),r=terrainChecks(l,s,load('data/m11a/baseline-r4-layout.json'));
fs.mkdirSync(path.join(root,'qa/m11a'),{recursive:true});fs.mkdirSync(path.join(root,'docs/m11a'),{recursive:true});
fs.writeFileSync(path.join(root,'data/m11a/terrain-resolved.json'),JSON.stringify(t.exportData(),null,2)+'\n');fs.writeFileSync(path.join(root,'qa/m11a/terrain-report.json'),JSON.stringify(r,null,2)+'\n');
let csv='facility_id,name,site_grade_H_m,floor_H_m,entry_rise_H_m,measured_m,status\n';for(const f of l.facilities){const a=t.anchors[f.id];csv+=`${f.id},${f.name.replaceAll(',','；')},${a?a.site.toFixed(3):''},${a?a.floor.toFixed(3):''},${a?a.rise.toFixed(3):''},,${a?'H_ASSUMED':'U_UNLOCATED'}\n`;}
fs.writeFileSync(path.join(root,'data/m11a/elevations.csv'),'\uFEFF'+csv);
let profiles='from,to,width_m,chainage_m,x,z,surface_H_m,max_slope_H\n';for(const p of t.profiles)for(const q of p.samples)profiles+=`${p.from},${p.to},${p.width},${q.distance.toFixed(3)},${q.x.toFixed(3)},${q.z.toFixed(3)},${q.y.toFixed(4)},${p.maxSlope.toFixed(6)}\n`;fs.writeFileSync(path.join(root,'data/m11a/road-profiles.csv'),profiles);
const esc=x=>String(x).replaceAll('&','&amp;').replaceAll('<','&lt;');
const chains=[['主路纵剖',l.navigation.mainRoadChain],['侧门至长雅路纵剖',l.navigation.requiredChains[0]],['主楼—厕所桥下—图书馆',l.navigation.requiredChains[1]]];
let svg='<svg xmlns="http://www.w3.org/2000/svg" width="1280" height="850" viewBox="0 0 1280 850"><rect width="1280" height="850" fill="#faf9f0"/><g font-family="Noto Sans CJK SC,Microsoft YaHei,sans-serif" fill="#24463e"><text x="55" y="42" font-size="25">M1.1-A · 相对标高纵剖 / H 工作方案</text><text x="55" y="70" font-size="13">横轴距离与纵轴标高采用不同图表比例；3D场景垂直夸张=1。主门为0m，不是海拔或现场测绘。</text>';
chains.forEach(([name,chain],i)=>{let distance=0,pts=[];for(let k=1;k<chain.length;k++){const pp=t.profile(chain[k-1],chain[k]);for(const q of pp)pts.push([distance+q.distance,q.y]);distance+=pp.at(-1).distance;}const top=118+i*225,base=top+145,scale=1000/Math.max(1,distance);svg+=`<text x="70" y="${top}" font-size="19">${esc(name)}</text>`;for(const h of [0,.2,.4,.6]){const y=base-h*160;svg+=`<path d="M100,${y}H1130" stroke="#d6dece"/><text x="60" y="${y+4}" font-size="12">${h.toFixed(1)}m</text>`;}svg+=`<polyline points="${pts.map(([x,y])=>(100+x*scale).toFixed(2)+','+(base-y*160).toFixed(2)).join(' ')}" fill="none" stroke="#427568" stroke-width="3"/><text x="100" y="${base+25}" font-size="12">0m</text><text x="1050" y="${base+25}" font-size="12">${distance.toFixed(1)}m 路程</text>`;});svg+='</g></svg>';fs.writeFileSync(path.join(root,'docs/m11a/road-profiles.svg'),svg);
if(!r.passed){console.error(r.results.filter(x=>!x.passed));process.exit(1);}console.log(`PASS ${r.results.length} terrain checks; ${t.profiles.length} frozen road segments exported.`);
