import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {build} from '../../apps/campus/node_modules/esbuild/lib/main.js';
const root=fileURLToPath(new URL('../../',import.meta.url)),out=path.join(root,'artifacts/m11b-b05');
await fs.mkdir(out,{recursive:true});
const result=await build({entryPoints:[path.join(root,'apps/campus/src/main.ts')],bundle:true,metafile:true,absWorkingDir:root,format:'iife',target:'es2022',minify:true,write:false,outfile:'bundle.js',legalComments:'inline'});
const js=result.outputFiles.find(f=>f.path.endsWith('.js')).text.replace(/<\/script/gi,'<\\/script'),css=result.outputFiles.find(f=>f.path.endsWith('.css')).text;
const template=await fs.readFile(path.join(root,'apps/campus/index.html'),'utf8');
const html=template.replace('</head>',`<style>${css}</style></head>`).replace('<script type="module" src="/src/main.ts"></script>',()=>`<script>${js}</script>`);
const name='Yali_B05_R1_Viewer.html',sha256=createHash('sha256').update(html).digest('hex');
await fs.writeFile(path.join(out,name),html);
const sourceFiles=[...new Set([...Object.keys(result.metafile.inputs).filter(f=>!f.includes('node_modules')).map(f=>path.relative(root,path.resolve(root,f))), 'apps/campus/index.html','apps/campus/package-lock.json'])].sort();
const sources={};for(const f of sourceFiles)sources[f]=createHash('sha256').update(await fs.readFile(path.join(root,f))).digest('hex');
await fs.writeFile(path.join(out,'viewer-manifest.json'),JSON.stringify({file:name,sha256,bytes:Buffer.byteLength(html),status:'IMPLEMENTED / REVIEW_PENDING',standard:'1.0',generatedAt:new Date().toISOString(),gitHead:execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim(),source:'current worktree; per-file digests identify source even before commit',sources},null,2));
const notices=await Promise.all(['three/LICENSE','three-mesh-bvh/LICENSE'].map(async f=>f+'\n'+await fs.readFile(path.join(root,'apps/campus/node_modules',f),'utf8')));await fs.writeFile(path.join(out,'THIRD_PARTY_NOTICES.txt'),notices.join('\n\n'));
console.log(name,Buffer.byteLength(html),sha256);
