/** Bind a completed, visually inspected browser run to the unmodified offline artifact.
 * This script verifies already obtained measurements. It never fabricates browser results.
 */
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {execFileSync} from 'node:child_process';
import {context} from './context.mjs';
const root=fileURLToPath(new URL('../../',import.meta.url));
const read=p=>fs.readFileSync(path.join(root,p)),json=p=>JSON.parse(read(p));
const hash=b=>createHash('sha256').update(b).digest('hex');
const put=(p,v)=>{fs.mkdirSync(path.dirname(path.join(root,p)),{recursive:true});fs.writeFileSync(path.join(root,p),typeof v==='string'?v:JSON.stringify(v,null,2)+'\n');};
const base='9e28225532718e3d60cc518aaac36ccc65f3fc2c',qa='qa/m11b-b05/final';
const viewer='artifacts/m11b-b05/Yali_B05_R1_Viewer.html',sha256=hash(read(viewer)),manifest=json('artifacts/m11b-b05/viewer-manifest.json');
assert.equal(manifest.sha256,sha256);
for(const [file,digest] of Object.entries(manifest.sources))assert.equal(hash(read(file)),digest,'Runtime source drift: '+file);
const counts={gate:4,courts:6,field:5,residential:3,checks:0,regression:8,mobile:3,fallback:3,performance:3,baseline:8};
const reports={};const allFiles=[];
for(const [group,count] of Object.entries(counts)){
 const r=json(`${qa}/${group}/report.json`);reports[group]=r;
 assert.equal(r.group,group);assert.equal(r.phase,'final');assert.equal(r.passed,true,group+' did not pass');assert.equal(r.views.length,count,group+' missing views');
 assert.equal(r.viewerSHA256,group==='baseline'?'d8e2b969802cfefcaba9d27da496f26ef8e9d1d85eb2a8bc7681d243f3002eda':sha256,'Mixed Viewer hash '+group);
 assert.equal(r.errors.length,0);assert.equal(r.externalRequests.length,0);
 for(const v of r.views){
  const file=`${qa}/${group}/${v.file}`,buffer=read(file);assert.equal(hash(buffer),v.sha256,'Screenshot hash '+file);
  assert.equal(buffer.subarray(1,4).toString(),'PNG');assert.equal(buffer.readUInt32BE(16),r.viewport.width);assert.equal(buffer.readUInt32BE(20),r.viewport.height);
  assert.equal(v.glError,0);assert.equal(v.contextLost,false);assert.ok(v.triangles>0);
  allFiles.push({file,sha256:v.sha256,group,view:v.view,method:v.screenshotMethod??'Playwright viewport'});
 }
}
const inspected=json('docs/m11b/batch05/visual-review.json');assert.equal(inspected.viewerSHA256,sha256);assert.equal(inspected.reviewed,true);assert.equal(inspected.status,'REVIEWED / NO_BLOCKING_VISUAL_DEFECTS');
for(const group of Object.keys(counts).filter(g=>g!=='checks'))assert.ok(inspected.groups.includes(group),'Visual review missing '+group);
const checks=reports.checks;assert.equal(checks.access.passed,true);assert.equal(checks.inherited.b03.passed,true);assert.equal(checks.inherited.b04.passed,true);
assert.equal(checks.invariants.flagCount,3);assert.deepEqual(checks.invariants.axis,[73,73,73]);assert.equal(checks.invariants.mainFloor,3.45);assert.equal(checks.invariants.unlocated22,null);
for(const v of reports.performance.views)assert.equal(v.performance.samples,60);
assert.equal(reports.mobile.mobile.noOverflow,true);assert.equal(reports.mobile.mobile.shadowResolution,2048);
assert.ok(reports.fallback.views.every(v=>v.lighting.logarithmicDepthBuffer&&!v.lighting.reversedDepthBuffer));
assert.match(read(`${qa}/build/tests.tap`).toString(),/# pass 17\b/);assert.match(read(`${qa}/build/tests.tap`).toString(),/# fail 0\b/);
assert.ok(!fs.existsSync(path.join(root,'data/m11b/batch05/acceptance.json')));
// Accepted geometry and all their source parameters remain bit-identical, not merely close.
const protectedFiles=execFileSync('git',['ls-tree','-r','--name-only',base],{cwd:root,encoding:'utf8'}).trim().split('\n').filter(p=>
 /^apps\/campus\/src\/(batch0[1-4]|shutter|r3-|patch0[234]|layout-core|terrain-core)/.test(p)||
 /^data\/m11b\/(batch0[1-4][^/]*|shutter-fix)\//.test(p)||/^data\/m11a\//.test(p));
const preservation={base,method:'byte-for-byte SHA256 of accepted source and data against Git object',files:{}};
for(const file of protectedFiles){const prior=execFileSync('git',['show',base+':'+file],{cwd:root,maxBuffer:50*1024*1024});assert.equal(hash(read(file)),hash(prior),file);preservation.files[file]=hash(prior);}
put(`${qa}/preservation.json`,preservation);
const {p,model,layout,terrain}=context();
put('data/m11b/batch05/effective-spatial.json',{batch:'B05',viewerSHA256:sha256,unit:'metre / H working coordinates, NOT survey',base,invariants:model.invariants,facilities:layout.facilities.map(f=>({id:f.id,name:f.name,position:f.position,size:f.size,floor:terrain.anchors[f.id]?.floor??null})),courtRects:model.courts,hoops:model.hoops,goals:model.goals,blocks:model.blocks,trees:model.trees,fenceSegments:model.fenceSegments,portals:model.portals,routes:model.routes});
const baseline=reports.baseline.scene,scene=reports.checks.scene;
const summary={batch:'B05',version:'R1',status:'IMPLEMENTED / REVIEW_PENDING',modelRenderingStandard:'1.0',viewer,viewerSHA256:sha256,viewerBytes:read(viewer).length,testedSourceCommit:reports.checks.sourceCommit,run:process.env.B05_VERIFIED_RUN??'34748491959',completedAt:new Date().toISOString(),build:'PASS',tests:{passed:17,failed:0,log:`${qa}/build/tests.tap`},browserGroups:Object.keys(counts),screenshots:{b05:allFiles.filter(f=>f.group!=='baseline').length,inheritedBaseline:8,files:allFiles},errors:[],externalRequests:[],warnings:Object.fromEntries(Object.entries(reports).map(([k,r])=>[k,r.warnings])),scene,baselineScene:baseline,sceneIncrease:{triangles:scene.triangles-baseline.triangles,geometryBytes:scene.geometryBytes-baseline.geometryBytes},catalogue:{parts:model.parts.length,trees:model.trees.length,hoops:model.hoops.length,goals:model.goals.length,housingBlocks:model.blocks.length},access:{passed:true,routes:checks.access.routes.length,portals:checks.access.doors.length,bodyOffsets:[-.34,0,.34],bodyHeights:[.26,1.1,1.9],maximumSupportSpacing:.6,supportTolerance:.225,minimumHeadroom:1.9,portalGrid:'3 widths × 3 heights; rendered triangles/BVH including inherited scene',report:`${qa}/checks/report.json`},inherited:{b02:checks.inherited.b02,b03:checks.inherited.b03.passed,b04:checks.inherited.b04.passed,invariants:checks.invariants,preservation:`${qa}/preservation.json`},performance:reports.performance.views.map(v=>({view:v.view,viewport:reports.performance.viewport,calls:v.calls,submittedTriangles:v.triangles,...v.performance})),environment:reports.performance.environment,mobile:reports.mobile.mobile,reflectionProbes:reports.regression.views[0].lighting.reflectionProbes,visualReview:'docs/m11b/batch05/visual-review.json',limitations:['All unmeasured placement/shape metrics and plant species/count remain H.','Rostrum cover chronology is H/U; photo is not proof of a 2006 cover.','Stone map-left side is inherited A; exact coordinates/orientation are unmeasured H.','22 remains unlocated; no invented shop.','Software GPU performance is not a device benchmark or frame-rate guarantee.','No physical first-person controller, full private interiors or dense small-plant landscaping in B05.'],acceptanceCreated:false};
put('qa/m11b-b05/final-summary.json',summary);
const fmt=n=>Number(n).toLocaleString('en-US'),performanceRows=summary.performance.map(v=>`| ${v.view} | ${v.samples} | ${v.medianMs.toFixed(2)} | ${v.p95Ms.toFixed(2)} | ${v.calls} | ${fmt(v.submittedTriangles)} |`).join('\n');
const routes=checks.access.routes.map(q=>`| ${q.id} | 0 |`).join('\n');
put('qa/m11b-b05/README.md',`# B05 R1｜实际浏览器 QA\n\n**工程检查通过 / IMPLEMENTED / REVIEW_PENDING**。用户认可尚未登记。\n\n受测源码：\`${summary.testedSourceCommit}\`。受测 Viewer：\`${viewer}\`，${fmt(summary.viewerBytes)} 字节，SHA256：\`${sha256}\`。原始10组报告均来自同次最终实际浏览器运行；B04基线8图明确绑定原B04哈希，不混入本批测试。\n\n## 结果\n\n生产构建通过；几何/材质/真实门洞/BVH定向测试17/17。B05 ${summary.access.routes}条路线、${summary.access.portals}处门洞通过；旧B02/B03/B04入口通过。所有最终组JS/GL错误0，外部请求0。保留截图恢复警告，见 [机器报告](final-summary.json) 和每组 report.json。初始窄屏390×844重新加载，2048阴影，无横向溢出；EXT_clip_control缺失模拟实际走对数深度并覆盖近景、顶视/主轴。\n\n本批${summary.screenshots.b05}张实际浏览器图，另8张本次重拍B04同机位基线。查看 [离线截图审阅页](review.html) 或 [视觉核查记录](../../docs/m11b/batch05/visual-review.json)。校门/泳池错误机位或截图超时的iteration-01历史保留；不据旧产物宣布新Viewer通过。\n\n| 全场景统计 | B04原Viewer（本次重拍） | B05受测Viewer |\n|---|---:|---:|\n| 可见模型三角面 | ${fmt(baseline.triangles)} | ${fmt(scene.triangles)} |\n| 唯一几何缓冲字节 | ${fmt(baseline.geometryBytes)} | ${fmt(scene.geometryBytes)} |\n| 网格对象 | ${baseline.meshes} | ${scene.meshes} |\n| 材质实例 | ${baseline.materials} | ${scene.materials} |\n\n全场景三角面不等于当前一帧提交面数。参数目录含${model.parts.length}构件、${model.hoops.length}个H篮架、${model.goals.length}球门、${model.trees.length}棵H定位主树和6个保留居住体量。原认可源码/参数逐文件校验见 [preservation.json](final/preservation.json)。\n\n## 实测成本，不是用户硬件FPS\n\n${summary.environment.browser} / ${scene.gpu}。1280×840，预热2帧，随后每机位60帧，调用同一render函数并gl.finish计CPU+GPU墙钟时间；暂停循环只为防止软件GPU抢占截图，不减少模型、阴影分辨率或材质。此数不可与旧rAF采样混算，也不能据此承诺普通设备帧率。\n\n| 机位 | 样本 | 中位ms | P95 ms | 绘制调用 | 单帧提交三角面 |\n|---|---:|---:|---:|---:|---:|\n${performanceRows}\n\n## 真实通行范围\n\n在完整可见场景和BVH上对路径侧向±0.34m、中心、三个身体高度采样；每0.6m以内校验地面和1.9m净空，门洞3×3网格。未引入人物物理控制器。\n\n| B05路线 | 失败数 |\n|---|---:|\n${routes}\n\n完整逐样本数据见 [checks/report.json](final/checks/report.json)，没有用飞行相机能穿墙代替通行结论。\n\n## 复现\n\n\`\`\`bash\nnpm ci --prefix apps/campus\nnpm run build --prefix apps/campus\nnode --test tests/m11b/b05/model.test.mjs tests/render-upgrade/*.test.mjs\nnode tools/m11b-b05/export.mjs\n# Playwright安装在外部目录，避免修改应用锁文件\nnpm install --prefix /tmp/yali-b05-browser playwright@1.62.0\n/tmp/yali-b05-browser/node_modules/.bin/playwright install --with-deps chromium\nexport PLAYWRIGHT_MODULE=/tmp/yali-b05-browser/node_modules/playwright\n# 新phase不覆盖本次归档；逐组也可在独立runner并行\nfor group in gate courts field residential checks regression mobile fallback performance baseline; do\n  B05_GROUP=$group B05_PHASE=reproduction node tools/m11b-b05/capture.mjs\ndone\n\`\`\`\n\nLinux图中文字需系统CJK字体，但本仓库及审阅包不分发字体。\n`);
const escape=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const cards=allFiles.map(f=>`<figure><a href="${escape(path.relative('qa/m11b-b05',f.file))}"><img loading="lazy" src="${escape(path.relative('qa/m11b-b05',f.file))}" alt="${escape(f.view)}"></a><figcaption>${escape(f.group)} · ${escape(f.view)}<small>${escape(f.method)}<br>SHA256 ${f.sha256}</small></figcaption></figure>`).join('\n');
put('qa/m11b-b05/review.html',`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>B05 R1 · 真实浏览器审阅</title><style>body{font:16px/1.6 system-ui,sans-serif;margin:0;background:#f1f2ef;color:#25322e}header{padding:32px;max-width:1200px;margin:auto}h1{margin:0}code{overflow-wrap:anywhere}main{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,520px),1fr));gap:20px;padding:20px}figure{margin:0;background:white;border:1px solid #d3d9d3}img{display:block;width:100%;height:340px;object-fit:contain;background:#dde2dc}figcaption{padding:16px;overflow-wrap:anywhere}small{display:block;font-size:11px;color:#53605b}a{color:#255e56}</style><header><h1>复原雅礼 · B05 R1</h1><p>校门、校园石、运动设施、主要植被与生活附属体量。IMPLEMENTED / REVIEW_PENDING。</p><p><a href="../../artifacts/m11b-b05/Yali_B05_R1_Viewer.html">打开离线 Viewer</a> · <a href="README.md">QA说明</a> · <a href="../../docs/m11b/batch05/evidence.md">照片与H边界</a></p><p>受测Viewer SHA256：<code>${sha256}</code></p><p>本页只展示实际浏览器画面。baseline分组为本次重拍的原B04，不是B05；其他分组均绑定上述SHA。所有定位尺寸H不视作实测。</p></header><main>${cards}</main></html>`);
put('docs/m11b/batch05/delivery.md',`# B05 R1｜交付\n\n状态：**IMPLEMENTED / REVIEW_PENDING**。本批没有登记acceptance；B01—B04（B03建筑R2，B04 R1）继续已认可。\n\n## 交付入口\n\n- [离线单文件Viewer](../../../artifacts/m11b-b05/Yali_B05_R1_Viewer.html)\n- [真实截图审阅页](../../../qa/m11b-b05/review.html)\n- [QA及复现命令](../../../qa/m11b-b05/README.md) · [机器报告](../../../qa/m11b-b05/final-summary.json)\n- [证据/H边界](evidence.md) · [28项覆盖](../../../data/m11b/batch05/coverage.json) · [同源实际位置/路线](../../../data/m11b/batch05/effective-spatial.json)\n\nViewer SHA256：\`${sha256}\`；${fmt(summary.viewerBytes)}字节。受测源码：\`${summary.testedSourceCommit}\`；实际测试run：\`${summary.run}\`。最终文档/截图归档的提交可能晚于受测源码，但工具会逐文件验证运行源码hash没有漂移。\n\n## 实际范围\n\n非对称主校门、开放伸缩门、侧置最小值班室；独立侧门；原-X侧校园石/可辨英文/低绿化；原六片篮球场、12个H悬臂篮架、蓝围网及东西门口；有顶直跑道及横向开口；原运动场/两端白色球门及背网；主席台及上下接入；原三旗台上的浅色栏杆；57棵确定性主树及低种植边界；泳池/池旁厕所、后缘沙坑；单层体育辅助体量；原生活区六体量立面/屋盖/公共入口与H短路。\n\n没有重排认可路网、高差、运动场、主轴或既有建筑。22小店仍未落位，不虚构商户。不是全室内装修、密集花草或正式人物玩法。\n\n## 标准与检查\n\n采用模型/材质/渲染标准**v1.0**。共享17类表面、色板、日光、天空、静态反射及深度/BVH继续沿用；新增四处探针，不移动旧七处。新4/8mm网丝使用8段截面，结构近景杆仍48段、篮圈32×192、树冠detail4；原因及边界见evidence。无照片贴图、bloom、暗角、景深、字体分发。\n\n生产构建和17项定向测试通过；完整场景21路线/14门洞及B02—B04入口检查通过；${summary.screenshots.b05}张本批实际图＋8张同次B04基线；桌面/390×844初始移动界面/顶视/主轴/真实反向与模拟对数回退均检查。${fmt(scene.triangles)}可见模型三角面、${fmt(scene.geometryBytes)}字节几何缓冲。真实性证据不足与软件GPU性能限制没有因测试通过而消失。\n\n## 审阅重点与边界\n\n校园石左右关系已经继承A，但**没有精确历史测量落点**；当前\`[-17,0,1]\`与正面方向为H工作坐标。主席台上盖时代仍H/U。12个篮架、球门规格、57棵树和生活区具体立面均是可替换H。截图中的主要树冠按共享简化风格表达，不宣称树种/树龄准确。\n\n首次迭代存在泳池被体育馆屋盖遮挡的错误机位及校门截图超时；保留其历史报告，不用旧截图充当修正版。最终受测Viewer与每张图哈希在QA中绑定；视觉复核见 [visual-review.json](visual-review.json)。\n\n认可B05后才能登记acceptance并决定合并main；随后才进入M1.1-C真实步行/碰撞/接地与连桥楼梯通行整合。\n`);
const live='## B05 当前交付（2026-09-13）\n\n**IMPLEMENTED / REVIEW_PENDING**。校门/校园石、六片球场篮架与围网、球门、主席台/三旗台、主要植被和生活附属体量已实施；不移动B01—B04已认可几何。校园石精确位置、主席台上盖年代、个体植被与隐蔽面继续H/U。 [B05交付](docs/m11b/batch05/delivery.md) · [QA/真实截图](qa/m11b-b05/README.md) · [Viewer](artifacts/m11b-b05/Yali_B05_R1_Viewer.html)。尚未登记B05认可；M1.1-C等待此批审阅。\n\n';
let readme=read('README.md').toString();if(readme.startsWith('## R3.1'))readme=readme.slice(readme.indexOf('# 复原雅礼'));if(!readme.includes('## B05 当前交付'))readme=readme.replace('## 当前状态',live+'## 当前状态');readme=readme.replace(/## 当前状态[^\n]*/, '## 当前状态：B01—B04 已认可，B05 已实现待审');readme=readme.replace('只剩B05校门及体育生活附属建筑。','B05外壳与主要固定校园构件已实现待审。');put('README.md',readme);
let plan=read('docs/development-plan.md').toString();if(plan.startsWith('## R3.1'))plan=plan.slice(plan.indexOf('# 开发计划'));plan=plan.replace(/^# 开发计划[^\n]*/,'# 开发计划｜2026-09-13 · B01—B04已认可 / B05已实现待审');plan=plan.replace(/\| M1\.1-B 第五批 B05 \|[^\n]*/, '| M1.1-B 第五批 B05 | IMPLEMENTED / REVIEW_PENDING | 剩余外壳、校门/石、球架/门/围网、主席台/三旗台、主要植被 |');plan=plan.replace('B05 尚未开始。','B05已按扩展任务书实现，等待本批审阅。').replace('下一批按 [B05启动任务书](m11b/batch05/start-next-thread.md) 进入最后一批建筑外壳。','B05已按扩展启动任务书完成工程实现与真实QA，当前等待本批审阅。');
plan=plan.replace(/## 第五批 B05：[\s\S]*?(?=## 建筑批次之后)/,`## 第五批 B05：建筑外壳与主要校园固定构件（已实现待审）\n\n[B05交付](m11b/batch05/delivery.md) · [实际QA](../qa/m11b-b05/README.md)。本批不仅是校门、风雨直跑道、低矮体育辅助用房和生活区外壳，还包含校园石的位置/朝向核对、12个H篮球架、蓝围网与可达门口、两端球门、原操场标线、主席台、三旗台栏杆及57棵H主要植被。泳池/旧小厕所、后缘沙坑一并处理必要外壳和入口。\n\nB01—B04的建筑及道路高差不变；生活区延续原六体量，公共短路H可替换。校园石-X左右关系继承，米制落点未实测；主席台上盖年代仍H/U；22小店仍U未落位。覆盖范围详见28项登记，不能将28个设施理解为28栋建筑。\n\nB05工程完成为IMPLEMENTED / REVIEW_PENDING，用户明确认可后才登记acceptance。没有把主要植被全部推迟到M1.2，但零散花草/密集园艺、生活物件及完整内装仍在后续。本轮不开正式人物玩法。\n\n`);put('docs/development-plan.md',plan);
const inventory={viewerSHA256:sha256,files:allFiles};put('qa/m11b-b05/screenshots-manifest.json',inventory);
console.log(JSON.stringify({status:summary.status,viewerSHA256:sha256,screenshots:summary.screenshots.b05,baseline:8,routes:21,portals:14,scene}));
